# Generated by Django 5.1.4 on 2025-01-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("football_app", "0002_remove_player_birth_date_player_age"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="gender",
        ),
        migrations.AlterField(
            model_name="player",
            name="nationality",
            field=models.CharField(default="Select nationality...", max_length=200),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.CharField(default="Select team...", max_length=200),
        ),
    ]
